INSERT INTO "ICALTIMEREPORTS"."PERSON" (FIRSTNAME,LASTNAME,USERNAME,PASSWORD,USERROLE) VALUES ('Admin','Admin','admin','heslo','Administrator')
INSERT INTO "ICALTIMEREPORTS"."CALENDAR" (NAME,URL,PERSON_ID) VALUES ('plan1','file:/d:\skola\bp\plan1.ics',1)
INSERT INTO "ICALTIMEREPORTS"."CALENDAR" (NAME,URL,PERSON_ID) VALUES ('plan2','file:/d:\skola\bp\plan2.ics',1)

