INSERT INTO "ICALTIMEREPORTS"."PERSON" (FIRSTNAME,LASTNAME,USERNAME,PASSWORD) VALUES ('Jaroslav','Švelta','jsvelta','955db0b81ef1989b4a4dfeae8061a9a6')
INSERT INTO "ICALTIMEREPORTS"."CALENDAR" (NAME,URL,PERSON_ID) VALUES ('plan1','file:/d:\skola\bp\plan1.ics',1)
INSERT INTO "ICALTIMEREPORTS"."CALENDAR" (NAME,URL,PERSON_ID) VALUES ('plan2','file:/d:\skola\bp\plan2.ics',1)

